dir: "{{.InterfaceDir}}/_mock"
outpkg: mockery
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
with-expecter: true
packages:
  github.com/ideagate/client-controller/adapter/kubernetes:
    interfaces:
      IKubernetesAdapter: